# user apis

### get Admin user

GET http://localhost:8000/api/v1/admin-user


### create admin user

POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName" :"Rupesh",
    "lName" :"Adhikari",
    "email":"a@abc.com",
    "password": "1234567",
    "phone": "123456"
}

### login admin user

POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    
    "email":"a@abc.com",
    "password": "1234567"
    
}

